apiVersion: autoscaling/v1
kind: HorizontalPodAutoscaler
metadata:
  name: locust-worker
spec:
  maxReplicas: 30
  minReplicas: 3
  scaleTargetRef:
    apiVersion: extensions/v1beta1
    kind: Deployment
    name: locust-worker
  targetCPUUtilizationPercentage: 50
